#parameters.py

" parameter names and descriptions"

hap_description = [
    '(active intensity)',
    '(maximum azimuth angle (AVS))',
    '(minimum azimuth angle (AVS))',
    '(bottom haptic waveform effect (1-123))',
    '(top haptic waveform effect (1-123))',
    '(maximum elevation angle (AVS))',
    '(minimum elevation angle (AVS))',
    '(use roll or pitch, 0=roll, 1=pitch)',
    '(haptic mode: IMU (0) or AVS (1))',
    '(using multiplexer, 1=enabled)',
    '(offset left AVS angle)',
    '(offset right AVS angle)',
    '(offset IMU angle)',
    '(maximum pitch angle (IMU))',
    '(minimum pitch angle (IMU))',
    '(maximum roll angle about x-axis (IMU))',
    '(minimum roll angle about x-axis (IMU))',
    '(sense left AVS (1 or -1))',
    '(sense right AVS (1 or -1))',
    '(sense IMU (1 or -1))',
    '(trigger timer)',
    '(maximum yaw angle (IMU))',
    '(minimum yaw angle (IMU))'
]

avs_description = [
    '(bottom AVS node ID)',
    '(angular resolution)',
    '(background SIL meas mode)',
    '(background SIL threshold dB)',
    '(smoothing time constant)',
    '(event window)',
    '(number sources)',
    '(event threshold)',
    '(FFT number of bins)',
    '(FFT start bin)',
    '(FFT Hann window flag)',
    '(minimum angle change in degrees)',
    '(minimum peak change in dB)',
    '(minimum peak height in dB)',
    '(RPM harmonics)',
    '(send commands to ARES, default: 0 = disabled)',
    '(top AVS node ID)'
]

all_params = [
    'HAP_ACT_INT',
    'HAP_AZIMUTH_MAX',
    'HAP_AZIMUTH_MIN',
    'HAP_DRV_EFFECT_B',
    'HAP_DRV_EFFECT_T',
    'HAP_ELEV_MAX',
    'HAP_ELEV_MIN',
    'HAP_IMU_UP_DOWN',
    'HAP_MODE',
    'HAP_MULTIPLEX',
    'HAP_OFFSET_AVS_L',
    'HAP_OFFSET_AVS_R',
    'HAP_OFFSET_IMU',
    'HAP_PITCH_MAX',
    'HAP_PITCH_MIN',
    'HAP_ROLL_MAX',
    'HAP_ROLL_MIN',
    'HAP_SENSE_AVS_L',
    'HAP_SENSE_AVS_R',
    'HAP_SENSE_IMU',
    'HAP_TRIG_TIMER',
    'HAP_YAW_MAX',
    'HAP_YAW_MIN',
    #
    'AVS_BOT_NODE_ID',	
    'AVS_EVT_ANG_RES',	
    'AVS_EVT_BGSIL',	
    'AVS_EVT_BGSIL_DB',
    'AVS_EVT_BG_TC',
    'AVS_EVT_EVT_WIN',	
    'AVS_EVT_NUM_SRC',	
    'AVS_EVT_REL_DB',
    'AVS_FFT_NUM_BINS',
    'AVS_FFT_STRT_BIN',
    'AVS_FFT_WINDOW',
    'AVS_PK_MIN_BLNK',
    'AVS_PK_MIN_D_DB',
    'AVS_PK_MIN_HGHT',
    'AVS_PK_NUM_HARM',
    'AVS_SEND_ARES',
    'AVS_TOP_NODE_ID',
    ]